### ISSUE TITLE
running tests in Racket 6.1 - installed pict3d via raco pkg...

### ISSUE THREAD

**Issue by lduguid** [ntoronto/pict3d#1]
Welcome to DrRacket, version 6.1 [3m].
Language: racket [custom]; memory limit: 128 MB.
. ../../../../../.racket/6.1/pkgs/pict3d/pict3d/private/math/fl2dot.rkt:45:16: flpow2near: unbound identifier in module in: flpow2near

Cannot find a definition for flpow2near although it seems to be referenced in ;
 ./pict3d/private/math/typed-flv3.rkt
./pict3d/private/math/fl2dot.rkt

**Comment by ntoronto** [comment]
Racket 6.1.1 has been released since this was opened. This should be fixed now.
