### ISSUE TITLE
Freezes up using 100% CPU on a core

### ISSUE THREAD

**Issue by Pastaf** [ntoronto/pict3d#10]
I recently did a few things, so I am unsure of what is causing it, but since I installed Debian on this computer finally, and this was after your most recent batch of updates, pict3d is completely incapable of running.

What I did:
- Installed Debian Wheezy
- Updated it to Jessie for a few packages
- Installed Racket via apt
- Realized it wasn't a high enough version, downloaded it off of the official site instead, for 6.1.1
- Installed pict3d

Using #lang typed/racket works, but when I do (require pict3d), be it from the REPL or in the file itself, on normal or typed racket, with or without content, the background expansion never ends. I have tried multiple times, and each time when I've broken it, after as long as 45 minutes, the trace given is to this file:
https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/types/filter-ops.rkt

I have tried, in DrRacket:
- Putting in #lang racket (works)
- Putting in #lang typed/racket (works)
- Putting in #lang racket, then using (require pict3d) (freezes)
- Putting in #lang typed/racket then using (require pict3d) (freezes)
- Putting in #lang racket, then using (require pict3d) from the REPL (freezes)
- Putting in #lang typed/racket then using (require pict3d) from the REPL (freezes)
- Navigating to snowman.rkt, and running (freezes)

This consistantly will max out one core to 100% usage and sit as is. I have left the snowman.rkt test running, and it is still in background expansion after just over an hour. I will let you know if this EVER finishes. I have set maximum RAM to unlimited.

I don't really know what information I should provide for you, but I can provide any at a request. The debian install is almost entirely clean, with only a few programs installed, and the racket install shouldn't be errored, but as I said, I had some issues due to the wrong version initially (I uninstalled the old version using apt-get purge before installing the new one).

I can also check on the Windows installation (on this system) or a FreeBSD installation (on a different system) if requested.

**Comment by ntoronto** [comment]
Apparently, I've done something recently that makes Typed Racket in 6.1.1 take a very long time. Sam Tobin-Hochstadt (the creator of Typed Racket) has also notified me of this. I'll investigate.

**Comment by ntoronto** [comment]
I think I've narrowed it down to "pict3d/private/gui/user-types.rkt". I may have a fix ready soon.

**Comment by ntoronto** [comment]
I've just pushed an update that I've verified compiles on 6.1.1 and runs the snowman test.

**Comment by Pastaf** [comment]
Gotcha. I'm back now, it was still running.
I can verify it does work now.
