### ISSUE TITLE
GL inside of REPL is blank

### ISSUE THREAD

**Issue by Pastaf** [ntoronto/pict3d#11]
All of the tests whose visible item is within the REPL fail, including the tutorial, where the ones in a seperate window do work. This includes all of the tests besides snowman, fractal trees, sausage plant and spheres. 

By fail I mean the box that is brought up is blank white, leaving only the outline of where the box should be. This is not due to the updates you just made, this has been the case ever since I installed Debian.

Check the previous issues for my specs and comments on giving you more information.

**Comment by ntoronto** [comment]
If you click on the white box, does it render? That happens to me occasionally, and I haven't been able to track down the conditions for it.

**Comment by ntoronto** [comment]
I just fixed some concurrency issues. Can you please try again?

**Comment by Pastaf** [comment]
Sorry for taking so long! No, it does not work.

**Comment by Pastaf** [comment]
Nevermind, it does work! I somehow managed to... forget to actually update pict3d. Sorry!

**Comment by ntoronto** [comment]
No problem! I'm just happy to have another indicator that the concurrency issues have been wiped out. :D
