### ISSUE TITLE
(dir-dx (dir 1 0 0))

### ISSUE THREAD

**Issue by AlexKnauth** [ntoronto/pict3d#18]
. . dir-dx: contract violation
  expected: Pos?
  given: (dir 1.0 0.0 0.0)
  in: the 1st argument of
      (-> Pos? any)
  contract from: 
      <pkgs>/pict3d/pict3d/private/gui/user-types.rkt
  blaming: anonymous-module
   (assuming the contract is correct)
  at: <pkgs>/pict3d/pict3d/private/gui/user-types.rkt:58.1

**Comment by ntoronto** [comment]
Thanks! A fix is on its way. In the meantime, `(match-define (dir dx dy dz) ...)` works.

**Comment by ntoronto** [comment]
Fixed in 790761522bf1711b40957697fdf86d6e53868d26.
