### ISSUE TITLE
bug with pin?

### ISSUE THREAD

**Issue by AlexKnauth** [ntoronto/pict3d#19]
This program:
```
#lang racket
(require pict3d)
(define p
  (combine (sphere origin 1/2)
           (basis '+top (point-at (pos 0 0 1) (dir 0 0 1)))
           (basis '-top (point-at (pos 0 0 1) (dir 0 0 -1)))
           (basis '+left (point-at (pos 0 1 0) (dir 0 1 0)))
           (basis '-left (point-at (pos 0 1 0) (dir 0 -1 0)))))
(define p1 (group p 'p1))
(define p2 (group p 'p2))
(define p3 (group p 'p3))
(define p1+p2
  (pin p1 '(p1 +top) p2 '(p2 -top)))
(define p1+p2+p3
  (pin p1+p2 '(p1 +left) p3 '(p3 -left)))
p1+p2+p3
```
I expected it to produce three spheres: one at (pos 0 0 0), one at (pos 0 0 2), and one at (pos 0 2 0).
Instead it produces four spheres.  

Is this a bug?  Why is this happening?

**Comment by ntoronto** [comment]
Recent experience has shown me that 1) groups and pinning are more complicated than I had guessed, and 2) Pict3D is usually right about these things, which makes me feel dumb.

Here's what I think is going on: when you pin `p2` onto `p1`, you also pin *its groups* onto `p1`. So now there's another group with tag `+left`, and the second `pin` pins onto that as well.

If you have a recent version of Pict3D, hover the mouse over the extra sphere, right-click, and select "Copy Surface Data". Besides the position and normal, it'll put `'(p1 +top p2 +left p3)` on the clipboard.

**Comment by ntoronto** [comment]
Oh, and the path `'(p1 +left)` also matches `'(p1 +top p2 +left)`, which is perhaps counterintuitive.

**Comment by AlexKnauth** [comment]
Okay, I guess that makes sense.

So first, is there a way to avoid that, and second, should you update the docs to try explain that, because the docs say:

Does three things:
1. Transforms pict2 so that its group with path path2 aligns with the group in pict1 with path path1.
2. Ungroups the group in pict2 with path path2.
3. Combines the result with pict1.

Which seems to imply (to me anyway) that it doesn't do that?  Is there a better way to explain it?

**Comment by ntoronto** [comment]
Doesn't do what? Match `'(p1 +left)` with things like `'(p1 +top p2 +left)`, or also transform and pin the groups in pict2?

I'm not contradicting you - there's obviously a problem with the docs here. I'm just trying to figure out exactly how your mental model doesn't match with Pict3D's behavior so I can fix them. (The docs. And possibly your mental model. And possibly Pict3D's behavior. It's all on the table, man.)

**Comment by AlexKnauth** [comment]
My mental model was that in p1+p2, the group p2 would not be created as a sub-group of p1 +top, but that it would simply do the transformations it needed to do to line them up and then combine them.  

So that's not what it does, but now that I think about it with your explanation, what it does does make sense for something like pinning a arm on a robot body, where you might want to refer to the arm group as a subgroup of the robot group.

**Comment by AlexKnauth** [comment]
Also, it might be helpful to have an option that can tell it to raise an error instead of this:
`If there is more than one group in pict1 with path path1, pict2 is pinned to all of them.`
If I don't expect there to be more than one group with that path.
It makes sense for it to pin it to all groups with that path, but when I only expect one group to have that path, I would want to know if I was wrong by an error message instead of by a weird thing showing up where I didn't expect it.

**Comment by AlexKnauth** [comment]
A version of pin that would more closely represent my mental model would probably be this:
```racket
(: my-pin (->* [Pict3D (Listof Tag) Pict3D] [(Listof Tag)] Pict3D))
(define (my-pin p1 n1 p2 [n2 empty])
  (combine
   p1
   (relocate p2
             (get-group-transform p2 n2)
             (get-group-transform p1 n1))))
```
And then set-origin could be implemented like this:
```racket
(: my-set-origin (-> Pict3D (Listof Tag) Pict3D))
(define (my-set-origin p n)
  (relocate p (get-group-transform p n) identity-affine))
```
Where get-group-transform (probably needs a better name) looks like this:
```racket
(: get-group-transform (-> Pict3D (Listof Tag) Affine))
(define (get-group-transform p n)
  (: fail (-> Index Nothing))
  (define (fail m)
    (error 'get-group-transform "expected one group ~e; given a Pict3D with ~a groups tagged ~e" n m n))
  (define ts (map-group/transform p n (λ ([t : Affine] _) t)))
  (cond [(empty? ts)  (fail 0)]
        [(empty? (rest ts))  (first ts)]
        [else  (fail (length ts))]))

```
I think, but for some reason when I try to run these definitions, they take too long to run, or loop forever or something, so I can't test them.

**Comment by AlexKnauth** [comment]
Now when I try to test it I'm getting a DrRacket internal error saying:
```
call-as-current: contract violation
  expected: (-> any)
  given: #<procedure:gl-vector->type/cpointer/length>
  in: the 1st argument of
      (->*m ((-> any)) (evt? any/c) any)
  contract from: 
      (class ...vate/wx/cocoa/dc.rkt:44:31)
  blaming: <pkgs>/gui-lib/mred/private/wx/cocoa/dc.rkt
   (assuming the contract is correct)
  context...:
   /Applications/Racket/Racket v6.2.0.2/collects/racket/contract/private/blame.rkt:143:0: raise-blame-error16
   /Users/Alex/Library/Racket/snapshot-6.2.0.2/pkgs/pict3d/pict3d/private/gui/invisible-context.rkt:49:0: get-invisible-canvas-context
   /Users/Alex/Library/Racket/snapshot-6.2.0.2/pkgs/pict3d/pict3d/private/gui/untyped-master-context.rkt:25:6
   /Applications/Racket/Racket v6.2.0.2/collects/racket/private/more-scheme.rkt:370:13: hash-ref!
   /Users/Alex/Library/Racket/snapshot-6.2.0.2/pkgs/pict3d/pict3d/private/gui/pict3d-snip.rkt:116:7
   /Users/Alex/Library/Racket/snapshot-6.2.0.2/pkgs/pict3d/pict3d/private/gui/pict3d-snip.rkt:104:2: render-thread-loop
```

**Comment by AlexKnauth** [comment]
Actually for some reason now I'm getting that error even without trying to use my-pin or any of those.

**Comment by AlexKnauth** [comment]
Ok I ran raco setup and now it's working.  Anyway, does that look useful?

**Comment by ntoronto** [comment]
A version of `pin` that doesn't pin into multiple groups is definitely useful. I'm considering making that the behavior of `pin`, and adding a `pin*` that pins into zero or more groups (i.e. the current behavior).

I'm not sure why you don't want the pinned pict to be *in* the group it's pinned into, though. Can you say a bit more about the use you're putting it to?

**Comment by AlexKnauth** [comment]
I'm trying to make a program that shows ball-and-stick models of molecules.  I put each atom in a group, and record the group name in a data structure so I can look them up later.  I also have each element defined as a pict with groups analogous to +top, +left etc, and I was trying to pin those elements together.  Using pin, I end up with extra atoms coming off where they shouldn't, but using this, they don't:
```
(: my-pin (->* [Pict3D (Listof Tag) Pict3D] [(Listof Tag)] Pict3D))
(define (my-pin p1 n1 p2 [n2 empty])
  (combine
   p1
   (relocate p2
             (get-group-transform p2 n2)
             (get-group-transform p1 n1))))
```

**Comment by ntoronto** [comment]
Ah, the light finally switches on. I can think of other uses for something like `my-pin` now. I'll probably want something like it when I start creating Spinny Cube levels.

I like your `my-pin` as it is (though I'd add a `my-pin*` that pins onto multiple sites), as well as `get-group-transform`. They just need better names. (I think `find-group-transform` for the latter would be good.) I swear, I've spent 1/4 of Pict3D's design time just thinking up names...

**Comment by ntoronto** [comment]
Some of these look OK: http://www.thesaurus.com/browse/attach?s=t

**Comment by AlexKnauth** [comment]
Does this look like a good implementation of a my-pin* function?
```racket
(: my-pin* (->* [Pict3D (Listof Tag) Pict3D] [(Listof Tag)] Pict3D))
(define (my-pin* p1 n1 p2 [n2 empty])
  (define p1-ts (map-group/transform p1 n1 (λ ([t : Affine] _) t)))
  (define t2 (get-group-transform p2 n2))
  (combine
   p1
   (for/list ([t1 (in-list p1-ts)]) : (Listof Pict3D)
     (relocate p2 t2 t1))))
```

**Comment by AlexKnauth** [comment]
Or would this be better?
```racket
(: my-pin* (->* [Pict3D (Listof Tag) Pict3D] [(Listof Tag)] Pict3D))
(define (my-pin* p1 n1 p2 [n2 empty])
  (let ([p2 (set-origin p2 n2)])
    (combine
     p1
     (map-group/transform p1 n1 (λ ([t1 : Affine] _) (transform p2 t1))))))
```

**Comment by ntoronto** [comment]
Whether it's better to apply a composition of two transforms or the two transforms separately depends on how eagerly the scene database applies them. At the moment, I think the second version is slightly faster.

**Comment by ntoronto** [comment]
OK, the next update will have `find-group-transforms`, `find-group-transform`, `join` (your `my-pin`), `join*` (your `my-pin*`), `glue` (like `join` but ungroups) and `glue*`.

I think you may have found the true 3D analogues of `hc-append` et al.
