### ISSUE TITLE
Tutorial for newbies

### ISSUE THREAD

**Issue by richcole** [ntoronto/pict3d#2]
It would be great if your README.md contained a tutorial for newbies. Something along the lines of 

Install racket by following instructions here. Then

  raco pkg install pict3d

Then in the repl

  (spaceship)

or whatever is appropriate to run one of your demos. You could even explain a bit about the libraries and how to access the documentation.

A couple of simple tutorials taking one through the main aspects of the library would be cool. My main way of working is racket-mode in emacs with an opengl window in its own frame rather than a frame in the repl would be nice and live updating the view by executing repl commands.

I tried raco pkg install pict3d but it said

 raco pkg install pict3d
 raco pkg install: cannot infer package source type
  source: git://github.com/ntoronto/pict3d

Which I suppose means raco can't install the package. How do I install pict3d?

**Comment by Pastaf** [comment]
Until you write the documentation, why not comment the tests, as you want us to learn from them? It may be helpful. Although, documentation and a simple starter guide would be more so :)

**Comment by ntoronto** [comment]
That's a good idea, especially if the comments indicate what you can tweak to make meaningful changes.

The problem has been that I'd been planning to change the API too much. Currently, while basis objects provide a way to insert objects into a pict3d, there's no way to change or remove objects without reconstructing the pict3d from scratch. There's also the issue that transforming basis objects is done with right matrix multiplication, and everything else with left matrix multiplication. I've always felt that it represents a fragility in their design and possibly their use.

As the documentation stands (which it doesn't), only you mavericks who don't mind a lot of changes are willing to use Pict3D. :D

Anyway, I've finally decided on a new design that works much better. It allows naming groups of objects hierarchically, attaching groups together by pinning their bases, and functionally updating groups by name. I should have a preliminary version ready today, and I think it's final-ish enough to warrant documenting.

**Comment by Pastaf** [comment]
Great! I don't really mind lots of API changes myself. I would rather have to re-write some stuff once in a while over having an ugly, messy mash of legacy support and limitations on improvements to it.

**Comment by ntoronto** [comment]
I started adding comments to tests. Then I realized that the tests were too complicated. So I wrote simpler tests with comments. Then I realized that, using a few macros, I was only a couple of steps away from actual tutorials. So I wrote a few.

To read through them all, write this program:

```racket
#lang racket
(require pict3d/tutorials)
```

To read through just one, write something like this:

```racket
#lang racket
(require pict3d/tutorial/00)
```

There are currently four: `00` through `03`. Please let me know what you think.

**Comment by bb010g** [comment]
@ntoronto So...are we going to have tutorial tests? :D

They look nice!

**Comment by ntoronto** [comment]
Yes, there will be tests. Pop quizzes. Finals. Get studying!

Heads-up: I've just made an API change that will curl your eyebrows if you've written any significant programs. Pict3D's combinators accept only specialized vector and color types, and distinguish between position and direction vectors.

**Comment by ntoronto** [comment]
I've just pushed documentation. This made the tutorials redudant, so I've removed them.

The `README.md` file now has installation instructions, and I think the docs are complete enough that I can close this.
