### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by AlexKnauth** [ntoronto/pict3d#20]
Here:
https://github.com/ntoronto/pict3d/blob/master/pict3d/scribblings/pict3d.scrbl#L992
```racket
(basis 'left (point-at v dv) #:angle 30)
```
should be
```racket
(basis 'left (point-at v dv #:angle 30))
```

**Comment by AlexKnauth** [comment]
And here:
https://github.com/ntoronto/pict3d/blob/master/pict3d/scribblings/pict3d.scrbl#L799
Did you mean:
```racket
(dir- dv1 (dir-scale (dir-project dv1 dv2) s))
```
And here:
https://github.com/ntoronto/pict3d/blob/master/pict3d/scribblings/pict3d.scrbl#L808
Did you mean:
```racket
then @racket[(dir-reflect dv n)] is the object's new velocity
```

**Comment by ntoronto** [comment]
Yes to all. Thanks for catching these.

**Comment by ntoronto** [comment]
Fixed in the latest round of commits (finally).
