### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by AlexKnauth** [ntoronto/pict3d#24]
I just tried to install it again from the package server, and I got this error:
```
raco setup: --- building documentation ---
raco setup: 0 running: <pkgs>/pict3d/pict3d/scribblings/pict3d.scrbl
raco setup: 2 running: <pkgs>/pict3d/typed/opengl/typed-opengl.scrbl
eval: unable to replay evaluation of (render-pict3ds (begin (current-pict3d-width default-pict3d-width) (current-pict3d-height default-pict3d-height)))
  context...:
   /Applications/Racket/April-16/Racket v6.2.0.2/share/pkgs/racket-doc/unstable/sandbox.rkt:91:11
   /Applications/Racket/April-16/Racket v6.2.0.2/collects/racket/private/more-scheme.rkt:147:2: call-with-break-parameterization
   /Applications/Racket/April-16/Racket v6.2.0.2/share/pkgs/sandbox-lib/racket/sandbox.rkt:837:5: loop

  context...:
   /Applications/Racket/April-16/Racket v6.2.0.2/collects/setup/parallel-do.rkt:330:4: work-done method in list-queue%
   /Applications/Racket/April-16/Racket v6.2.0.2/collects/setup/parallel-do.rkt:280:17
   /Applications/Racket/April-16/Racket v6.2.0.2/collects/setup/parallel-do.rkt:234:4
   /Applications/Racket/April-16/Racket v6.2.0.2/share/pkgs/racket-index/setup/scribble.rkt:138:0: setup-scribblings
   /Applications/Racket/April-16/Racket v6.2.0.2/collects/setup/setup-core.rkt:69:0: setup-core
   /Applications/Racket/April-16/Racket v6.2.0.2/collects/setup/setup.rkt:65:3
   /Applications/Racket/April-16/Racket v6.2.0.2/collects/pkg/main.rkt:16:0: setup
   /Applications/Racket/April-16/Racket v6.2.0.2/share/pkgs/gui-lib/mrlib/terminal.rkt:210:7
   /Applications/Racket/April-16/Racket v6.2.0.2/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:454:6
   /Applications/Racket/April-16/Racket v6.2.0.2/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:505:32
   /Applications/Racket/April-16/Racket v6.2.0.2/collects/racket/private/more-scheme.rkt:147:2: call-with-break-parameterization
   /Applications/Racket/April-16/Racket v6.2.0.2/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:400:18: loop
```

**Comment by ntoronto** [comment]
Bah. I forgot that merging something that changes the docs breaks them.

As a workaround, you can open "pict3d.scrbl" in DrRacket and run it, and then rebuild from the command line.

**Comment by AlexKnauth** [comment]
Ok, it works now.

**Comment by AlexKnauth** [comment]
So if I end up with another pull request that changes the docs, what should I do to make sure it works, while still avoiding including all the files that running the scribble file produce?  What I did this time was I committed, ran the scribble file in drracket, and then in the github program, I clicked "discard changes."  Should I not discard those? Or should I discard some of them, but not all of them? Looking at another commit, should I not discard the changes to pict3d/scribblings/pict3d-log.rktd? Why is that necessary in the github repo?

**Comment by ntoronto** [comment]
Include that file. It's a recording of all the interactions in the documentation, run on a machine with a known-good configuration (e.g. mine or yours).

When the docs are built in DrRacket, the evaluator creates that file. When the docs are built from the command line, the evaluator reads that file and replays it. See `make-log-based-eval` in `unstable/sandbox`.
