### ISSUE TITLE
Not Possible to Install in Windows

### ISSUE THREAD

**Issue by FrHuang2000** [ntoronto/pict3d#26]
I have tried many windows computer and it is absolutely impossible to install in Windows 7

**Comment by ntoronto** [comment]
Can you paste in the error installation halts with?

**Comment by FrHuang2000** [comment]
Resolving "pict3d" via http://download.racket-lang.org/releases/6.1/catalog/
Resolving "pict3d" via http://pkgs.racket-lang.org
Downloading
https://github.com/ntoronto/pict3d/tarball/6d65a3a0857c78848644a8dd28df5feb2b2ce239
The following out-of-date packages are listed as dependencies of pict3d
and they will be automatically updated:
   base (have 6.1, need 6.1.1)
DrRacket install: package installed in a different scope
  package: base
  current scope: user
  installed in scope: installation

On Fri, May 1, 2015 at 1:44 PM, Neil Toronto <notifications@github.com>
wrote:

> Can you paste in the error installation halts with?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ntoronto/pict3d/issues/26#issuecomment-98231575>.
>



-- 
"Franklin" HongYi Huang

**Comment by ntoronto** [comment]
I'm pretty sure this means you'll need to upgrade to Racket 6.1.1 to use Pict3D. Head to http://download.racket-lang.org/ to get it - it's as easy as falling off a broomstick.

The error message could definitely use some TLC. I've posted on the Racket dev mailing list about improving it.

**Comment by FrHuang2000** [comment]
Thank you, the problem has been solved perfectly.

On Fri, May 1, 2015 at 5:51 PM, Neil Toronto <notifications@github.com>
wrote:

> Closed #26 <https://github.com/ntoronto/pict3d/issues/26>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ntoronto/pict3d/issues/26#event-295327391>.
>



-- 
"Franklin" HongYi Huang
