### ISSUE TITLE
would it be useful to allow transforms as well as tag-paths in join, set-origin, etc?

### ISSUE THREAD

**Issue by AlexKnauth** [ntoronto/pict3d#27]
Would it be useful to allow transforms as well as tag-paths in join, set-origin, etc?
For example:
```racket
(define p1 (cylinder origin 1/2))
(define p1-top (point-at (pos 0 0 1/2) +z))
(define p2 (cone origin 1/2))
(join p1 p1-top (move-z p2 1/2))
(define p2-bot (point-at (pos 0 0 -1/2) +z))
(join p1 p1-top p2 p2-bot)
```

**Comment by ntoronto** [comment]
I think it would. I've sometimes been annoyed at having to create named groups that I never use.

Can you give equivalent code for one of your examples just so I can be completely sure I know what you mean?

**Comment by AlexKnauth** [comment]
The code for my examples would be equivalent to the examples for join here:
http://pkg-build.racket-lang.org/doc/pict3d/combining-scenes.html#%28def._%28%28lib._pict3d%2Fmain..rkt%29._join%29%29

**Comment by ntoronto** [comment]
Ah, and the only change to the code would be changing e.g. `(find-group-transform pict1 path1)` to something that uses the path-or-transform argument directly if it's a transform?

**Comment by AlexKnauth** [comment]
I think that would be good enough for join and set-origin, but I'm not sure if other code might need to be changed to support that for other functions like those?
