### ISSUE TITLE
Raco says invalid deps specification

### ISSUE THREAD

**Issue by richcole** [ntoronto/pict3d#4]
After pulling the latest master version and running with my racket daily snapshot from a few weeks ago I got the following error:

richcole@beast:~/install/pict3d$ raco pkg install
raco pkg install: invalid `deps' specification
  specification: '(("base" '#:version "6.1.1") "draw-lib" "srfi-lite-lib" "typed-racket-lib" "typed-racket-more" "math-lib" "scribble-lib")

richcole@beast:~/install/pict3d$ racket --version
Welcome to Racket v6.1.1.1.

If I replace ("base" '#:version "6.1.1") with "base". The compile starts. I don't know yet if it finishes. I have 8 cores and 8 GB. It was running out of memory previously before it could complete.

**Comment by ntoronto** [comment]
Has this problem gone away since Racket 6.1.1 was released?

**Comment by ntoronto** [comment]
I just merged a pull request from Asumu that fixes the dependency syntax in the info file. Maybe now it's fixed. :D

**Comment by ntoronto** [comment]
Asumu's fix apparently works. Closing.
